server:
  port: 9000

spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.110:8848
        namespace: ddc57837-c29e-4e51-846d-1feb554be9d0


